version: '3.8'

services:
  backend:
    image: phungquocquy/mern-backend:1.0
    container_name: mern_backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://phungquocquy23_db_user:77rxCcnhCW7BRUr0@cluster0.ftrmpdy.mongodb.net/?appName=Cluster0
    restart: always

  frontend:
    image: phungquocquy/mern-frontend:2.0
    container_name: mern_frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend
    restart: always